name: "Build & Deploy Page"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
   # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'
  pull_request: # only runs up through build of sphinx

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
    - name: Install doxygen and graphviz
      run: sudo apt-get install -y doxygen graphviz
    - name: Build multiversion with API
      run: make multiversion-with-api
    - name: clone gh-pages branch
      uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
      with:
        ref: gh-pages
        path: gh-pages
    - name: Commit documentation changes
      # if: github.event_name != 'pull_request'
      run: |
        cp -r _build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      # if: ${{ github.event_name != 'pull_request' && !env.ACT }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
